package com.jqmkj.java.web.filter;

import com.jqmkj.java.common.config.JqmkjProperties;
import com.jqmkj.java.common.security.SecurityUtil;
import com.jqmkj.java.util.PublicUtil;
import com.jqmkj.java.util.spring.SpringContextHolder;
import org.springframework.web.filter.OncePerRequestFilter;

import javax.servlet.FilterChain;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;

/**
 * Filter used to put the CSRF token generated by Spring Security in a cookie for use by AngularJS.
 */
public class PageInitParamFilter extends OncePerRequestFilter {

    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
        JqmkjProperties jqmkjProperties = SpringContextHolder.getBean(JqmkjProperties.class);
        String basePath =  jqmkjProperties.getGatewayModel() ? "" : PublicUtil.toAppendStr(request.getScheme(), "://", request.getServerName(), ":", request.getServerPort(), request.getContextPath());
        request.setAttribute("basePath", basePath);
        if(PublicUtil.isEmpty(jqmkjProperties.getContextPath())){
            jqmkjProperties.setContextPath(request.getContextPath());
        }
        String adminPath = jqmkjProperties.getAdminPath();
        request.setAttribute("ctx", PublicUtil.toAppendStr(basePath, (jqmkjProperties.getGatewayModel() ? "../" + jqmkjProperties.getMicorservice() : "") + adminPath));
        request.setAttribute("gatewayModel", jqmkjProperties.getGatewayModel());
        request.setAttribute("assets", PublicUtil.toAppendStr(basePath, "/statics/assets"));
        request.setAttribute("ctxStatic", PublicUtil.toAppendStr(basePath, "/statics/frame"));
        request.setAttribute("application", jqmkjProperties.getApplication());
        HttpSession session = request.getSession();
        if (session.getAttribute("moduleList") == null && PublicUtil.isNotEmpty(SecurityUtil.getCurrentUserIdWithNoException())) {
            session.setAttribute("moduleList", SecurityUtil.getModuleList());
        }
        filterChain.doFilter(request, response);
    }
}
